---
title: "penguin_assignment.Rmd"
output: html_document
date: "2022-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = FALSE, message=FALSE)
```

## Initial Setup:
```{r}
#Set the working directory - where R will look for files and folders
#setwd(set own working directory personal to your machine) - root directory should be "penguins-main"

#Load the libraries from the libraries function from my file
source("functions/libraries.r")

#Load the functions for cleaning the data and plotting from my files
source("functions/cleaning.r")
source("functions/plotting.r")

#Load the data:
penguins_raw <- read.csv("data_raw/penguins_raw.csv")
```

## Clean the data:
```{r}
#Fix column names, remove empty rows, remove columns beginning with delta and comments
penguins_clean <- cleaning(penguins_raw)


# Save the clean data with current date in the title
date = Sys.Date() 
filename = paste("data_clean/", date, "_penguins_clean.csv",sep="") 
# e.g. "data_clean/2022-12-08_penguins_clean.csv"
write.csv(penguins_clean, filename)

#Subset the data to only include penguins that are not NA for body mass and sex, 
#and reformat wording
penguins_mass <- mass_data_cleaning(penguins_clean)

#Save this data we will use for analysis
filename = paste("data_clean/", date, "_penguins_mass.csv",sep="" 
# e.g. "data_clean/2022-12-08_penguins_mass.csv"
write.csv(penguins_mass, filename)
```


## Statistical analysis
```{r}
#I want to test for the effect of sex, species, and the interaction between the two on the body mass of three species of penguin.
#Building a linear model
model1 <- lm(body_mass_g ~ sex*species, penguins_mass)

#generating the anova
anova(model1)
```
```{r}
#then generating the summary table for this model
summary(model1)
```


## Plotting a figure to explain this test:
```{r}
#Plot the body mass by sex and species
mass_barchart <- plot_mass_figure(penguins_mass)
mass_barchart
```

#Saving the figure for different purposes:
```{r}
#Save the figure for a report
save_mass_barchart_png(penguins_mass, "figures/fig01_report.png",
size = 15, res = 600, scaling = 1)
```


```{r}
#Save the figure for a presentation
save_mass_barchart_png(penguins_mass, "figures/fig01_presentation.png",
                       size = 15, res = 600, scaling = 1.4)
```


```{r}
#Save the figure for a poster
save_mass_barchart_png(penguins_mass, "figures/fig01_poster.png",
                       size = 35, res = 600, scaling = 2.8)
```


```{r}
#Save the figure as a vector, for screen viewing
save_mass_barchart_svg(penguins_mass, "figures/fig01_vector.svg",
                      size=15, scaling=1)
```

